
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 27 15:44:19 GMT 2014
//----------------------------------------------------

package Analyser;

/** CUP generated interface containing symbol constants. */
public interface Sym {
  /* terminals */
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int ANY = 2;
  public static final int ID = 3;
  public static final int INT = 4;
  public static final int EQUALS = 5;
  public static final int PLUS = 6;
  public static final int TIMES = 7;
  public static final int ASSIGN = 8;
  
  

  /* non terminals */
  static final int grammar = 0;
}

